trigger:
- master

pr:
- master

variables:
 # Values retrieved from Azure Key Vault secrets can not be shown or printed using e.g. "echo" to keep them save.
 # In our case we just post them to a simple container which can reflect the posted content to display the versioned values. 
 # The postpath here is just an IP of a container instance running danielmeixner/httpmirror
 postpath: 51.137.0.119/write


pool:
  vmImage: 'ubuntu-latest'

steps:

# Get specific version (newer) of secret
- task: AzureKeyVault@1
  inputs:
    azureSubscription: 'keyvaultaccess'
    KeyVaultName: 'minerva-keyvault'
    
    ## Secret should return red
    SecretsFilter: 'mycolorsecret/842d53ebca294fc18331ff1086910353'
    
    # Secret should return blue
    #SecretsFilter: 'mycolorsecret/dafe24d8399f41b38a7883bf8bd9ff6c'
    
    # Secret should return green
    #SecretsFilter: mycolorsecret/80b8d4540bfb407b90e15a5eb3b3a87e
  displayName: 'Get versioned secret'

  

- script: |      
    # red
    curl $(postpath)?value=$(mycolorsecret/842d53ebca294fc18331ff1086910353)
    
    # blue 
    # curl $(postpath)?value=$(mycolorsecret/dafe24d8399f41b38a7883bf8bd9ff6c)
    
    # green
    #curl $(postpath)?value=$(mycolorsecret/80b8d4540bfb407b90e15a5eb3b3a87e)
    
  displayName: 'Post new value'
